In [1]:
# data cleaning

In [2]:
import pandas as pd
import numpy as np

In [5]:
data = {
    "Name":["Ram","Krishna","Sita","Gita","srijala","pabitra"],
    "Age":[25,30,  np.nan,30,28,38],
    "City":["Ktm","brt", "rjb",None,None,"ltp"],
    "Salary":[5000,6000,7000,6000,np.nan,9000]
}
df = pd.DataFrame(data)
df
cpydf =df

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0
2     Sita   NaN  rjb  7000.0
3     Gita  30.0  NaN  6000.0
4      NaN  28.0  NaN     NaN

In [6]:
df.isnull()

    Name    Age   City  Salary
0  False  False  False   False
1  False  False  False   False
2  False   True  False   False
3  False  False   True   False
4   True  False   True    True

In [7]:
df.isnull().sum() #find out how mNY NULL

Name      1
Age       1
City      2
Salary    1
dtype: int64

In [8]:
#deleting null row
df.dropna()

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0

In [9]:
ndf = df.dropna() #new data frame

In [10]:
ndf

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0

In [17]:
#deleting null in column
cdf = df.dropna(axis=1)
cdf

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [20]:
df_clean = df.dropna(axis=0) #delete all the row that have null
df_clean

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0

In [ ]:
#cols_with_nan = df.columns[df.isnull().any()]
#df = df.drop(columns=cols_with_nan)

In [22]:
# filling missing value with zero
dfz = df.fillna(0)
dfz

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0
2     Sita   0.0  rjb  7000.0
3     Gita  30.0    0  6000.0
4        0  28.0    0     0.0

In [23]:
dfz = df.fillna(1)
dfz

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0
2     Sita   1.0  rjb  7000.0
3     Gita  30.0    1  6000.0
4        1  28.0    1     1.0

In [24]:
df

      Name   Age City  Salary
0      Ram  25.0  Ktm  5000.0
1  Krishna  30.0  brt  6000.0
2     Sita   NaN  rjb  7000.0
3     Gita  30.0  NaN  6000.0
4      NaN  28.0  NaN     NaN

In [32]:
# fillinfg with age coulmn with mean value
mean_age = df['Age'].mean()

In [33]:
df["Age"] = df["Age"].fillna(mean_age)

In [34]:
df

      Name    Age City  Salary
0      Ram  25.00  Ktm  5000.0
1  Krishna  30.00  brt  6000.0
2     Sita  28.25  rjb  7000.0
3     Gita  30.00  NaN  6000.0
4      NaN  28.00  NaN     NaN

In [35]:
df["Age"] = df["Age"].fillna(df['Age'].median())

In [36]:
df

      Name    Age City  Salary
0      Ram  25.00  Ktm  5000.0
1  Krishna  30.00  brt  6000.0
2     Sita  28.25  rjb  7000.0
3     Gita  30.00  NaN  6000.0
4      NaN  28.00  NaN     NaN

In [37]:
df

      Name    Age City  Salary
0      Ram  25.00  Ktm  5000.0
1  Krishna  30.00  brt  6000.0
2     Sita  28.25  rjb  7000.0
3     Gita  30.00  NaN  6000.0
4      NaN  28.00  NaN     NaN

In [38]:
#forward filled
#df = df.ffill()

In [39]:
#df

      Name    Age City  Salary
0      Ram  25.00  Ktm  5000.0
1  Krishna  30.00  brt  6000.0
2     Sita  28.25  rjb  7000.0
3     Gita  30.00  rjb  6000.0
4     Gita  28.00  rjb  6000.0

In [40]:
df = df.bfill()

In [46]:
df

      Name    Age City  Salary
0      Ram  25.00  Ktm  5000.0
1  Krishna  30.00  brt  6000.0
2     Sita  28.25  rjb  7000.0
3     Gita  30.00  rjb  6000.0
4     Gita  28.00  rjb  6000.0

In [47]:
#
duplicates = df.duplicated()

In [48]:
duplicates

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
df = df.drop_duplicates()

In [50]:
df

      Name    Age City  Salary
0      Ram  25.00  Ktm  5000.0
1  Krishna  30.00  brt  6000.0
2     Sita  28.25  rjb  7000.0
3     Gita  30.00  rjb  6000.0
4     Gita  28.00  rjb  6000.0