In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name":["Rakesh","Sikha","Anil","Priya","Anya","Anya],
    "Age":[25,30,22,28,35,5],
    "Salary":[5000,7000,4500,6500,8000,2000],
    "City":["Rajbiraj","Biratnagar","Kathmandu","Pokhara","Kathmandu","pokhara"]
})

In [31]:
df

     Name  Age  Salary        City   Bnous  Age_month
4    ANYA  420    8000   Kathmandu  9600.0       5040
1   SIKHA  360    7000  Biratnagar  8400.0       4320
3   PRIYA  336    6500     Pokhara  7800.0       4032
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
2    ANIL  264    4500   Kathmandu  5400.0       3168

In [4]:
df['Bnous'] = df['Salary'] * 1.20 # add bonus in salary

In [5]:
df

     Name  Age  Salary        City   Bnous
0  Rakesh   25    5000    Rajbiraj  6000.0
1   Sikha   30    7000  Biratnagar  8400.0
2    Anil   22    4500   Kathmandu  5400.0
3   Priya   28    6500     Pokhara  7800.0
4    Anya   35    8000   Kathmandu  9600.0

In [6]:
df['Name']= df['Name'].str.upper()#changinf into capital

In [7]:
df

     Name  Age  Salary        City   Bnous
0  RAKESH   25    5000    Rajbiraj  6000.0
1   SIKHA   30    7000  Biratnagar  8400.0
2    ANIL   22    4500   Kathmandu  5400.0
3   PRIYA   28    6500     Pokhara  7800.0
4    ANYA   35    8000   Kathmandu  9600.0

In [8]:
df['City'] = df['City'].str.lower()

In [9]:
df

     Name  Age  Salary        City   Bnous
0  RAKESH   25    5000    rajbiraj  6000.0
1   SIKHA   30    7000  biratnagar  8400.0
2    ANIL   22    4500   kathmandu  5400.0
3   PRIYA   28    6500     pokhara  7800.0
4    ANYA   35    8000   kathmandu  9600.0

In [10]:
df['City'] = df['City'].str.title()

In [11]:
df

     Name  Age  Salary        City   Bnous
0  RAKESH   25    5000    Rajbiraj  6000.0
1   SIKHA   30    7000  Biratnagar  8400.0
2    ANIL   22    4500   Kathmandu  5400.0
3   PRIYA   28    6500     Pokhara  7800.0
4    ANYA   35    8000   Kathmandu  9600.0

In [12]:
df['City'] = df['City'].replace('Kathmandu','Kathmandu capital')

In [14]:
df

     Name  Age  Salary        City   Bnous
0  RAKESH   25    5000    Rajbiraj  6000.0
1   SIKHA   30    7000  Biratnagar  8400.0
2    ANIL   22    4500   Kathmandu  5400.0
3   PRIYA   28    6500     Pokhara  7800.0
4    ANYA   35    8000   Kathmandu  9600.0

gender = {
    "Rakesh": "Male",
    "Sikha": "Female",   
    "Anil": "Male",
    "Priya": "Female",
    "Anya": "Female"
}

In [ ]:
df['Gender']= df['Name'].map(gender)

In [16]:
df

     Name  Age  Salary        City   Bnous
0  RAKESH   25    5000    Rajbiraj  6000.0
1   SIKHA   30    7000  Biratnagar  8400.0
2    ANIL   22    4500   Kathmandu  5400.0
3   PRIYA   28    6500     Pokhara  7800.0
4    ANYA   35    8000   Kathmandu  9600.0

In [18]:
df['Name'].unique()

<StringArray>
['RAKESH', 'SIKHA', 'ANIL', 'PRIYA', 'ANYA']
Length: 5, dtype: str

In [19]:
df["Age"] = df["Age"] * 12

In [20]:
df

     Name  Age  Salary        City   Bnous
0  RAKESH  300    5000    Rajbiraj  6000.0
1   SIKHA  360    7000  Biratnagar  8400.0
2    ANIL  264    4500   Kathmandu  5400.0
3   PRIYA  336    6500     Pokhara  7800.0
4    ANYA  420    8000   Kathmandu  9600.0

In [21]:
df['Age_month']= df['Age'] *12

In [22]:
df

     Name  Age  Salary        City   Bnous  Age_month
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
1   SIKHA  360    7000  Biratnagar  8400.0       4320
2    ANIL  264    4500   Kathmandu  5400.0       3168
3   PRIYA  336    6500     Pokhara  7800.0       4032
4    ANYA  420    8000   Kathmandu  9600.0       5040

In [23]:
sorted_df = df.sort_values(by = 'Age')

In [24]:
sorted_df

     Name  Age  Salary        City   Bnous  Age_month
2    ANIL  264    4500   Kathmandu  5400.0       3168
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
3   PRIYA  336    6500     Pokhara  7800.0       4032
1   SIKHA  360    7000  Biratnagar  8400.0       4320
4    ANYA  420    8000   Kathmandu  9600.0       5040

In [25]:
sorted_df = df.sort_values(by = 'Age', ascending = False)

In [26]:
sorted_df

     Name  Age  Salary        City   Bnous  Age_month
4    ANYA  420    8000   Kathmandu  9600.0       5040
1   SIKHA  360    7000  Biratnagar  8400.0       4320
3   PRIYA  336    6500     Pokhara  7800.0       4032
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
2    ANIL  264    4500   Kathmandu  5400.0       3168

In [27]:
df.sort_values(by = ["Age","Salary"], ascending = [False,True], inplace = True)

In [28]:
df

     Name  Age  Salary        City   Bnous  Age_month
4    ANYA  420    8000   Kathmandu  9600.0       5040
1   SIKHA  360    7000  Biratnagar  8400.0       4320
3   PRIYA  336    6500     Pokhara  7800.0       4032
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
2    ANIL  264    4500   Kathmandu  5400.0       3168

In [33]:
df.sort_values(by="Age",inplace=True)

In [34]:
df

     Name  Age  Salary        City   Bnous  Age_month
2    ANIL  264    4500   Kathmandu  5400.0       3168
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
3   PRIYA  336    6500     Pokhara  7800.0       4032
1   SIKHA  360    7000  Biratnagar  8400.0       4320
4    ANYA  420    8000   Kathmandu  9600.0       5040

In [36]:
df.sort_values(by="Age").reset_index(drop=True)

     Name  Age  Salary        City   Bnous  Age_month
0    ANIL  264    4500   Kathmandu  5400.0       3168
1  RAKESH  300    5000    Rajbiraj  6000.0       3600
2   PRIYA  336    6500     Pokhara  7800.0       4032
3   SIKHA  360    7000  Biratnagar  8400.0       4320
4    ANYA  420    8000   Kathmandu  9600.0       5040

In [39]:
df = df[df['Age'] >270]

In [40]:
df

     Name  Age  Salary        City   Bnous  Age_month
0  RAKESH  300    5000    Rajbiraj  6000.0       3600
3   PRIYA  336    6500     Pokhara  7800.0       4032
1   SIKHA  360    7000  Biratnagar  8400.0       4320
4    ANYA  420    8000   Kathmandu  9600.0       5040

In [43]:
df = df[(df['Age'] >270)&(df['Salary']<8000)]

In [45]:
df

     Name  Age  Salary      City   Bnous  Age_month
0  RAKESH  300    5000  Rajbiraj  6000.0       3600

In [49]:
df = df[(df['Age'] > 250) & (df['City'].isin(["kathmandu"]))]

In [50]:
df

Empty DataFrame
Columns: [Name, Age, Salary, City, Bnous, Age_month]
Index: []

In [ ]:
ctni df[~df["Cit