In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department":["IT","HR","IT","Finance","HR","Finance"],
    "Employee":["Rakesh","Sikha","Anil","Priya","John","Ram"],
    "Salary":[5000,6000,7000,8000,5500,9000],
    "Age":[25,30,28,35,32,40]
})

In [3]:
#sum of salary by department
sal_sum = df.groupby('Department')['Salary'].sum()
sal_sum

Department
Finance    17000
HR         11500
IT         12000
Name: Salary, dtype: int64

In [4]:
print(type(sal_sum))

<class 'pandas.Series'>

In [6]:
sal_mean = df.groupby('Department')['Salary'].mean()
sal_mean

Department
Finance    8500.0
HR         5750.0
IT         6000.0
Name: Salary, dtype: float64

In [7]:
dept_count = df.groupby('Department')['Salary'].count()
dept_count

Department
Finance    2
HR         2
IT         2
Name: Salary, dtype: int64

In [8]:
dept_min = df.groupby('Department')['Salary'].min()
dept_min

Department
Finance    8000
HR         5500
IT         5000
Name: Salary, dtype: int64

In [9]:
dept_max = df.groupby('Department')['Salary'].max()
dept_max

Department
Finance    9000
HR         6000
IT         7000
Name: Salary, dtype: int64

In [10]:
result = df.groupby("Department").agg({
    "Salary":["sum","mean","max"],
    "Age":["min","max"]
})

In [11]:
result

           Salary               Age
              sum    mean   max min max
Department
Finance     17000  8500.0  9000  35  40
HR          11500  5750.0  6000  30  32
IT          12000  6000.0  7000  25  28

In [12]:
df

  Department Employee  Salary  Age
0         IT   Rakesh    5000   25
1         HR    Sikha    6000   30
2         IT     Anil    7000   28
3    Finance    Priya    8000   35
4         HR     John    5500   32
5    Finance      Ram    9000   40

In [13]:
#total salary of it department
total_it_dept_sal = df[df['Department'] == 'IT']['Salary'].sum()
total_it_dept_sal

np.int64(12000)

In [14]:
#calculate average salary of it department
total_it_dept_salmean = df[df['Department'] == 'IT']['Salary'].mean()
total_it_dept_salmean

np.float64(6000.0)

In [16]:
#calculATE diffrence of sal betn itdept and finance dept
total_it_dept_sal = df[df['Department'] == 'IT']['Salary'].sum()
total_finance_dept_sal = df[df['Department'] == 'Finance']['Salary'].sum()
difference =  total_finance_dept_sal - total_it_dept_sal 
difference

np.int64(5000)

In [17]:
#sum on basis of department and gender
#res = df.groupby(['Department','Gender'])['Salary'].sum()

In [24]:
gender = {
    "Rakesh":"Male",
    "Sikha":"Female",
    "Anil":"Male",
    "Priya":"Female",
    "John":"Male",
    "Ram":"Male"
}
df['Gender'] = df['Employee'].map(gender)
df

  Department Employee  Salary  Age Gensder  Gender
0         IT   Rakesh    5000   25    Male    Male
1         HR    Sikha    6000   30  Female  Female
2         IT     Anil    7000   28    Male    Male
3    Finance    Priya    8000   35  Female  Female
4         HR     John    5500   32    Male    Male
5    Finance      Ram    9000   40    Male    Male

In [25]:
res = df.groupby(['Department','Gender'])['Salary'].sum()
res

Department  Gender
Finance     Female     8000
            Male       9000
HR          Female     6000
            Male       5500
IT          Male      12000
Name: Salary, dtype: int64

# avg salary and count

In [22]:
result = (
    df.groupby("Department")
    .agg(
        Average_Salary=("Salary","mean"),
        Employee_Count=("Employee","count")
    )
    .reset_index()
)
print(result)

  Department  Average_Salary  Employee_Count
0    Finance          8500.0               2
1         HR          5750.0               2
2         IT          6000.0               2

In [26]:
print(result['Department'])

0    Finance
1         HR
2         IT
Name: Department, dtype: str

In [27]:
print(result['Average_Salary'])

0    8500.0
1    5750.0
2    6000.0
Name: Average_Salary, dtype: float64

In [29]:
print(result['Employee_Count'])

0    2
1    2
2    2
Name: Employee_Count, dtype: int64

In [30]:
print(result['Average_Salary'][0])

8500.0