In [1]:
import pandas as pd

df1 = pd.DataFrame({
    "Name":["Rakesh","Sikha"],
    "Age":[25,30],
})
df2 = pd.DataFrame({
    "Name":["Anil","Priya"],
    "Age":[22,28]
})

In [6]:
cdf = pd.concat([df1,df2], ignore_index=True)

In [18]:
cdf

     Name  Age
0  Rakesh   25
1   Sikha   30
0    Anil   22
1   Priya   28

In [8]:
df3 = pd.DataFrame({
    "salary":[5000,7000,8000,9000]
})

In [ ]:
dfc = pd.concat([cdf,df3],axis =1)

In [ ]:
dfc

In [11]:
#merging :
employees = pd.DataFrame({
    "EmpID":[1,2,3],
    "Name":["Rakesh","Sikha","Anil"],
})
salaries = pd.DataFrame({
    "EmpID":[1,2,4],
    "Salary":[5000,7000,6000]
})

In [12]:
mdf = pd.merge(employees,salaries, on = 'EmpID')

In [13]:
mdf

   EmpID    Name  Salary
0      1  Rakesh    5000
1      2   Sikha    7000

In [14]:
ldf = pd.merge(employees,salaries, on = 'EmpID', how ="left")

In [15]:
ldf

   EmpID    Name  Salary
0      1  Rakesh  5000.0
1      2   Sikha  7000.0
2      3    Anil     NaN

In [16]:
rdf = pd.merge(employees,salaries, on = 'EmpID', how ="right")

In [17]:
rdf

   EmpID    Name  Salary
0      1  Rakesh    5000
1      2   Sikha    7000
2      4     NaN    6000

In [ ]:
employees = pd.DataFrame({
    "EmpID":[1,2,3],
    "Name":["Rakesh","Sikha","Anil"],
})
salaries = pd.DataFrame({
    "EmpID":[1,2,4],
    "Salary":[5000,7000,6000]
})

In [19]:
#outer merge
outer_merge = pd.merge(employees,salaries, on = 'EmpID', how ="outer")

In [20]:
outer_merge

   EmpID    Name  Salary
0      1  Rakesh  5000.0
1      2   Sikha  7000.0
2      3    Anil     NaN
3      4     NaN  6000.0

In [22]:
#join it combine dataframe in basis of index
left = pd.DataFrame({
    "Name":["Rakesh","Sikha","Anil"]
}, index=[1,2,3])
right = pd.DataFrame({
    "Salary":[5000,7000,6000]
}, index=[1,2,4])

In [23]:
df = left.join(right)

In [24]:
df

     Name  Salary
1  Rakesh  5000.0
2   Sikha  7000.0
3    Anil     NaN

In [25]:
#inner join
inner = left.join(right, how="inner") #only common
print(inner)

     Name  Salary
1  Rakesh    5000
2   Sikha    7000

In [26]:
left.join(right, how="right")

     Name  Salary
1  Rakesh    5000
2   Sikha    7000
4     NaN    6000

In [27]:
outer = left.join(right, how="outer") #only common
print(outer)

     Name  Salary
1  Rakesh  5000.0
2   Sikha  7000.0
3    Anil     NaN
4     NaN  6000.0

In [28]:
orders = pd.DataFrame({
    'order_id':[1,2,3,4],
    'costumer_id':[101,102,103,104],
    'amount': [250,150,300,200]
})

customers = pd.DataFrame({
    'customer_id':[101,102,105],
    'name' : ['Alice','Bob','Eve']
})

In [29]:
cdf = pd.concat([orders,customers], ignore_index=True)

In [30]:
cdf

   order_id  costumer_id  amount  customer_id   name
0       1.0        101.0   250.0          NaN    NaN
1       2.0        102.0   150.0          NaN    NaN
2       3.0        103.0   300.0          NaN    NaN
3       4.0        104.0   200.0          NaN    NaN
4       NaN          NaN     NaN        101.0  Alice
5       NaN          NaN     NaN        102.0    Bob
6       NaN          NaN     NaN        105.0    Eve