In [1]:
# feature envineering process of using domain knowledge to extract features from raw data
#-creates new feaature from existing one
# feature selection say we must select useful feature
# reduce unnecessary feature also reduce dimension 
# we do to prove accuracy

In [6]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'Age':[25,np.nan,30],
    'Salary':[50000,60000,70000]
})
print(df)

    Age  Salary
0  25.0   50000
1   NaN   60000
2  30.0   70000

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

    Age  Salary
0  25.0   50000
1  27.5   60000
2  30.0   70000

In [8]:
df = pd.DataFrame({
    'Age':[2,np.nan,30,28,35,np.nan],
    'Salary':[50000,60000,70000,55000,900000,65000],
    'Gender':['Male','Female','Male','Female','Female','Male'],
    'Department':[ 'HR','IT','Finance','IT','HR','Marketing'],
    'City':['Kathmandu','Pokhara','Kathmandu','Pokhara','Lalitpur','Birgunj']
})
df

    Age  Salary  Gender Department       City
0   2.0   50000    Male         HR  Kathmandu
1   NaN   60000  Female         IT    Pokhara
2  30.0   70000    Male    Finance  Kathmandu
3  28.0   55000  Female         IT    Pokhara
4  35.0  900000  Female         HR   Lalitpur
5   NaN   65000    Male  Marketing    Birgunj

In [9]:
# create new feature#
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0,18,30,50,100],
    labels=['Young','Adult','Middle_Age','Senior']
)
print(df[['Age','Age_Group']])

    Age   Age_Group
0   2.0       Young
1   NaN         NaN
2  30.0       Adult
3  28.0       Adult
4  35.0  Middle_Age
5   NaN         NaN

In [10]:
df['Salary_Level'] = pd.cut(
    df['Salary'],
    bins=[0,60000,100000,float('inf')],
    labels=['Low','Medium','High']
)
print(df[['Salary','Salary_Level']])

   Salary Salary_Level
0   50000          Low
1   60000          Low
2   70000       Medium
3   55000          Low
4  900000         High
5   65000       Medium

In [11]:
df

    Age  Salary  Gender Department       City   Age_Group Salary_Level
0   2.0   50000    Male         HR  Kathmandu       Young          Low
1   NaN   60000  Female         IT    Pokhara         NaN          Low
2  30.0   70000    Male    Finance  Kathmandu       Adult       Medium
3  28.0   55000  Female         IT    Pokhara       Adult          Low
4  35.0  900000  Female         HR   Lalitpur  Middle_Age         High
5   NaN   65000    Male  Marketing    Birgunj         NaN       Medium

In [12]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first',sparse_output=False)
encoded = encoder.fit_transform(df[['Gender','Department','City']])
encoded

array([[1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0.]])

In [13]:
df_encoded =pd.get_dummies(
    df,
    columns=['Gender','Department','City','Age_Group','Salary_Level'],
    dtype=int
)
print(df_encoded)

    Age  Salary  Gender_Female  Gender_Male  Department_Finance  \
0   2.0   50000              0            1                   0
1   NaN   60000              1            0                   0
2  30.0   70000              0            1                   1
3  28.0   55000              1            0                   0
4  35.0  900000              1            0                   0
5   NaN   65000              0            1                   0

   Department_HR  Department_IT  Department_Marketing  City_Birgunj  \
0              1              0                     0             0
1              0              1                     0             0
2              0              0                     0             0
3              0              1                     0             0
4              1              0                     0             0
5              0              0                     1             1

   City_Kathmandu  City_Lalitpur  City_Pokhara  Age_Group_Young  \
0               1              0             0                1
1               0              0             1                0
2               1              0             0                0
3               0              0             1                0
4               0              1             0                0
5               0              0             0                0

   Age_Group_Adult  Age_Group_Middle_Age  Age_Group_Senior  Salary_Level_Low  \
0                0                     0                 0                 1
1                0                     0                 0                 1
2                1                     0                 0                 0
3                1                     0                 0                 1
4                0                     1                 0                 0
5                0                     0                 0                 0

   Salary_Level_Medium  Salary_Level_High
0                    0                  0
1                    0                  0
2                    1                  0
3                    0                  0
4                    0                  1
5                    1                  0

In [17]:
encoded_df = pd.DataFrame(encoded,
                          columns=encoder.get_feature_names_out(['Gender','Department','City']))
encoded_df

,Gender_Male,Department_HR,Department_IT,Department_Marketing,City_Kathmandu,City_Lalitpur,City_Pokhara
0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [14]:
df

    Age  Salary  Gender Department       City   Age_Group Salary_Level
0   2.0   50000    Male         HR  Kathmandu       Young          Low
1   NaN   60000  Female         IT    Pokhara         NaN          Low
2  30.0   70000    Male    Finance  Kathmandu       Adult       Medium
3  28.0   55000  Female         IT    Pokhara       Adult          Low
4  35.0  900000  Female         HR   Lalitpur  Middle_Age         High
5   NaN   65000    Male  Marketing    Birgunj         NaN       Medium

In [15]:
X = df.drop(columns=['Salary'])
X

    Age  Gender Department       City   Age_Group Salary_Level
0   2.0    Male         HR  Kathmandu       Young          Low
1   NaN  Female         IT    Pokhara         NaN          Low
2  30.0    Male    Finance  Kathmandu       Adult       Medium
3  28.0  Female         IT    Pokhara       Adult          Low
4  35.0  Female         HR   Lalitpur  Middle_Age         High
5   NaN    Male  Marketing    Birgunj         NaN       Medium

In [16]:
Y = df['Salary']
Y

0     50000
1     60000
2     70000
3     55000
4    900000
5     65000
Name: Salary, dtype: int64

In [17]:
bonus = 0.01* df['Salary']
Salary_Bonus = Y + bonus 
Salary_Bonus

0     50500.0
1     60600.0
2     70700.0
3     55550.0
4    909000.0
5     65650.0
Name: Salary, dtype: float64